import struct
DEFAULT_BASE_OUT = r"D:\gesture_project\cnn_version_test\五通道最终版本"
DEFAULT_MODEL_DIR = DEFAULT_BASE_OUT + r"\models"
DEFAULT_MODEL_PATH = DEFAULT_MODEL_DIR + r"\cnn_window_model.pt"
DEFAULT_LABEL_PATH = DEFAULT_MODEL_DIR + r"\label_map.npy"
DEFAULT_NORM_PATH = DEFAULT_MODEL_DIR + r"\norm_stats.npz"

DEFAULT_USE_ONLINE_FLEX_DIFF = True
DEFAULT_WINDOW_LEN = 18
DEFAULT_INFER_EVERY_N_SAMPLES = 1
DEFAULT_SMOOTH_VOTE_N = 3
DEFAULT_PRINT_EVERY_SEC = 0.02

DEFAULT_REST_LABEL = "0"
DEFAULT_LABEL_STABLE_MS = 80
DEFAULT_QUICK_TAP_MAX_MS = 1500
DEFAULT_LONG_HOLD_MIN_MS = 2000
DEFAULT_DOUBLE_TAP_GAP_MS = 2000
DEFAULT_ENTER_CONFIRM_MS = 400

DEFAULT_PIPELINE_ENABLED = True
DEFAULT_PIPELINE_NAME = "pipeline1"
DEFAULT_PIPELINE_SEQUENCE = "1,2,3"
DEFAULT_PIPELINE_STEP_GAP_MS = 1000
DEFAULT_PIPELINE_COOLDOWN_MS = 1200

DEFAULT_TASK_ENABLED = False
DEFAULT_TASK_NAME = "task1"
DEFAULT_TASK_TARGET_TYPE = "label"
DEFAULT_TASK_TARGET_NAME = ""
DEFAULT_TASK_LABEL_MODE = "either"
DEFAULT_TASK_DURATION_SEC = 10.0
DEFAULT_TASK_REQUIRED_COUNT = 5
DEFAULT_MOUSE_CONTROL_ENABLED = False

GESTURE_TYPE_OPTIONS = ["either", "tap", "long_hold"]
TASK_TARGET_TYPE_OPTIONS = ["label", "pipeline"]
TASK_LABEL_MODE_OPTIONS = ["either", "tap", "long_hold"]
MOUSE_ACTION_OPTIONS = ["move_left", "move_right", "move_up", "move_down", "recenter", "click"]
DEFAULT_MOUSE_ACTION = "move_left"
DEFAULT_MOUSE_MOVE_SPEED = 35

DEFAULT_HOST_IP = "0.0.0.0"
DEFAULT_SENSOR_PORT = 5005
DEFAULT_ARDUINO2_IP = "10.133.138.6"
DEFAULT_CMD_PORT = 6006
DEFAULT_UDP_SEND_ENABLED = True

SIGNAL_OPTIONS = [f"signal{i}" for i in range(6)]

APP_STATE_PATH = "gesture_monitor_state.json"
DEFAULT_GESTURE_LIBRARY_IMAGE_PATH = ""

HEADER_STRUCT = struct.Struct("<HHI")
FRAME_STRUCT = struct.Struct("<I5Hhh")
FRAME_SIZE = FRAME_STRUCT.size
HEADER_SIZE = HEADER_STRUCT.size
BATCH_FRAME_COUNT = 5
BATCH_SIZE = HEADER_SIZE + BATCH_FRAME_COUNT * FRAME_SIZE
PACKET_MAGIC = 0x4753
PACKET_VERSION = 1

